options:
  allocations-instances-ignored:
    default: ""
    type: string
    description: |
      Comma separated list of VM UUIDs to ignore in placement checks.
  check-allocations:
    default: True
    type: boolean
    description:
      Switch to turn on or off check for allocation inconsistencies between nova and placement.
  check-dns:
    default: ""
    type: string
    description: |
      A space-separated list of DNS names to check.  If any of the names are not resolvable, alert as CRITICAL.
  check-neutron-agents:
    default: True
    type: boolean
    description: |
      Switch to turn on or off neutron agents checks. By default, neutron_agents nrpe check is enabled.
      If a different SDN (ie. Contrail) is in use, you may want to disable this check.
  check-port-security:
    default: False
    type: boolean
    description: |
      Switch to turn on or off check for port security.
      If hardware offloading is used on a port, port security must be disabled.
  check-octavia:
    default: True
    type: boolean
    description: |
      Switch to turn on or off check for octavia services.
  check-masakari:
    default: False
    type: boolean
    description: |
      Switch to turn on or off check for masakari segment hosts
  check-horizon:
    default: False
    type: boolean
    description: |
      Switch to turn on or off check for horizon connectivity and login.
      A website relation with openstack-dashboard(horizon) is a prerequisite. 
  octavia-loadbalancers-ignored:
    type: string
    default: ""
    description: |
      Comma separated list of octavia load balancer alerts to ignore
  octavia-amphorae-ignored:
    type: string
    default: ""
    description: |
      Comma separated list of octavia amphorae alerts to ignore
  octavia-pools-ignored:
    type: string
    default: ""
    description: |
      Comma separated list of octavia pool alerts to ignore
  octavia-image-ignored:
    type: string
    default: ""
    description: |
      Comma separated list of octavia image alerts to ignore
  octavia-amp-image-tag:
    default: "octavia-amphora"
    type: string
    description: |
      The glance image tag octavia will use to create amphora.
  octavia-amp-image-days:
    default: 365
    type: int
    description: |
      If latest glance image tagged with above octavia-amp-image-tag is updated more than these days ago,
      a Nagios warning will be raised. The version of octavia agent builtin in amphora image must match
      version of octavia controller, otherwise octavia will fail to communicate with new amphora,
      failover will also fail.
  check-rally:
    default: False
    type: boolean
    description: |
      Switch to turn on or off rally checks via the fcbtest snap. By default, rally nrpe check is disabled.
  skip-rally:
    default: ""
    type: string
    description: |
      Comma separated list of OpenStack components to not monitor. An empty string means all components will be
      monitored (up to the number of currently supported components: Cinder, Glance, Nova, Neutron).
      Sample: skip-rally=cinder
  rally-cron-schedule:
    default: "*/15 * * * *"
    type: string
    description: |
      Cron schedule used to run the rally tests. Default value is every 15 minutes.
      Furthermore, the cronjob is scheduled to time out after 13 minutes (SIGTERM) or 14 minutes (SIGKILL).
  os-credentials:
    default: ""
    type: string
    description: |
      Comma separated OpenStack credentials to be used by nagios.
      It is strongly recommended this be a user with a dedicated role,
      and not a full admin.  Takes the format of
      username=foo, password=bar, credentials_project=baz, region_name=Region1, auth_url=http://127.0.0.1:35357, volume_api_version=3
  nova_warn:
    default: 2
    type: int
    description: |
      Warning level for nova aggregate unit count check - setting this to -1 will effectively disable host aggregate checks.
  nova_crit:
    default: 1
    type: int
    description: |
      Critical level for nova aggregate unit count check - setting this to -1 will effectively disable host aggregate checks.
  skipped_host_aggregates:
    type: string
    default: ""
    description: |
      Comma separated list of host aggregates that need to be skipped from checks. Example "Agg1,AGg2" or 'Aggregate3'.
      This is a case-insensitive option.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  trusted_ssl_ca:
    type: string
    default: ''
    description: |
      base64 encoded SSL ca cert to use for OpenStack API client connections.
  skip-disabled:
    type: boolean
    default: false
    description: |
      An option to specify whether you want Warning alerts in nagios for disabled nova-compute hosts.
  tls_warn_days:
    type: int
    default: 30
    description: |
      Number of days left for the TLS certificate to expire before warning.
  tls_crit_days:
    type: int
    default: 14
    description: |
      Number of days left for the TLS certificate to expire before alerting Critical.
  check_public_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'public' URLs in the Keystone catalog.
  check_internal_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'internal' URLs in the Keystone catalog.
  check_admin_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'admin' URLs in the Keystone catalog.
  swift_check_params:
    type: string
    default: "/"
    description: |
      URL to use with check_http if there is a Swift endpoint.  Default is '/', but it's possible to add extra params,
      e.g. '/v3 -e Unauthorized -d x-openstack-request-id' or a different url, e.g. '/healthcheck'.  Mitaka Swift
      typically needs '/healthcheck'.
  s3_check_params:
    type: string
    default: "/healthcheck"
    description: |
      URL to use with check_http if there is an S3 endpoint.  Default is '/healthcheck', but it's possible to add extra params,
      e.g. '/v3 -e Unauthorized -d x-openstack-request-id' or a different url, e.g. '/' (when the endpoint is used with
      ceph-radosgw for example).
  contrail_analytics_vip:
    type: string
    default: ''
    description: The VIP used for Contrail Analytics. Leave blank to disable Contrail monitoring.
  contrail_ignored_alarms:
    type: string
    default: 'vrouter,'
    description: Comma separated list of contrail alerts to ignore
  email_recipients:
    type: string
    default: ''
    description: Comma separated list of email recipients to send notifications on demand.
  email_from_addr:
    type: string
    default: ''
    description: From address when sending email notifications.
  check-networks:
    description: |
      List of OpenStack networks IDs to be checked by NRPE check. All values
      must be separated by a comma and the value `all` is not allowed.
    type: string
    default: ""
  check-subnets:
    description: |
      List of OpenStack subnets IDs to be checked by NRPE check. All values
      must be separated by a comma and the value `all` is not allowed.
    type: string
    default: ""
  check-security-groups:
    description: |
      List of OpenStack security group IDs to be checked by NRPE check.
      All values must be separated by a comma and the value `all` is not
      allowed.
    type: string
    default: ""
  check-ports:
    description: |
      List of OpenStack ports IDs to be checked by NRPE check. All values
      must be separated by a comma or 'all' can be entered.
    type: string
    default: "all"
  skip-ports:
    description: |
      List of OpenStack ports IDs to be skipped by the NRPE check.
      All values must be separated by a comma. The condition for using this
      option is to set "check-ports" to "all" or this value will raise
      an error.
    type: string
    default: ""
  check-floating-ips:
    description: |
      List of OpenStack floating ips IDs to be checked by NRPE check. All
      values must be separated by a comma or 'all' can be entered.
    type: string
    default: "all"
  skip-floating-ips:
    description: |
      List of OpenStack floating ips IDs to be skipped by the NRPE check.
      All values must be separated by a comma. The condition for using
      this option is to set "check-floating-ips" to "all" or this value
      will raise an error.
    type: string
    default: ""
  check-servers:
    description: |
      List of OpenStack servers IDs to be checked by NRPE check. All values
      must be separated by a comma or 'all' can be entered.
    type: string
    default: "all"
  skip-servers:
    description: |
      List of OpenStack servers IDs to be skipped by the NRPE check.
      All values must be separated by a comma. The condition for using this
      option is to set "nrpe-server-ids" to "all" or this value will raise
      an error.
    type: string
    default: ""
