name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-unit:
    uses: canonical/bootstack-actions/.github/workflows/lint-unit.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10"]
    with:
      python-version: ${{ matrix.python-version }}
      working-directory: ./src

  func:
    uses: ['self-hosted', 'x64', 'jammy', 'xlarge']
    needs: lint-unit
    strategy:
      fail-fast: false
      matrix:
        command: ["TEST_JUJU3=1 make functional"]  # TEST_JUJU3 needed due https://github.com/openstack-charmers/zaza/blob/b22c2eed4c322f1dfc14ffb2d31e0dd18c911a40/setup.py#L47 to support Juju3+
        juju-channel: ["3.4/stable"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Juju ${{ matrix.juju-channel }} environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: ${{ matrix.juju-channel }}
          bootstrap-options: '--bootstrap-constraints="virt-type=virtual-machine mem=8G"'
      - name: Run functional tests
        run: ${{ matrix.command }}
